routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@home')->name('index');

Route::get('/aboutus', 'HomeController@aboutus')->name('aboutus');

Route::get('/contact', 'HomeController@contact')->name('contact');

Route::get('/terms-and-conditions', 'HomeController@terms')->name('terms');

Route::get('/office-outdoors', 'HomeController@officeOutdoors')->name('office-outdoors');

Route::get('/vagafam', 'HomeController@vagafam')->name('vagafam');

Route::get('category/{slug}', 'HomeController@categoryProfile')->name('category-profile');

Route::get('trip/{slug}/{when?}', 'HomeController@tripProfile')->name('trip-profile');

Route::get('upcoming-trips', 'HomeController@experiences')->name('experiences');

Route::post('vagafam-form', 'HomeController@vagafamForm')->name('vagafam.form');

Route::post('officeoutdoors-form', 'HomeController@officeoutdoorsForm')->name('officeoutdoors.form');

Route::post('contact-form', 'HomeController@contactForm')->name('contact.form');

Route::middleware('guest')->group(function () {

	Route::get('login', 'LoginController@loginPage')->name('login-page');

	Route::post('login', 'LoginController@login')->name('login');

});

Route::middleware('auth')->group(function () {

	Route::prefix('admin')->group(function () {

		Route::resource('testimonials', 'TestimonialController');

		Route::get('testimonials/{testimonial}/delete', 'TestimonialController@delete')->name('testimonial.delete');

		Route::resource('slides', 'SlideController');

		Route::get('slides/{slide}/delete', 'SlideController@delete')->name('slide.delete');	

		Route::resource('category', 'CategoryController');

		Route::get('category/{category}/delete', 'CategoryController@delete')->name('category.delete');	

		Route::post('category/{category}/icon', 'CategoryController@icon')->name('category.icon');

		Route::get('category/{category}/icon/delete', 'CategoryController@iconDelete')->name('category.icon.delete');	

		Route::resource('trips', 'ItemController');

		Route::get('trip/{trip}/delete', 'ItemController@delete')->name('trip.delete');

		Route::resource('images', 'ImageController');

		Route::get('images/{image}/delete', 'ImageController@delete')->name('image.delete');

		Route::resource('artists', 'ArtistController');

		Route::get('artists/{artist}/delete', 'ArtistController@delete')->name('artist.delete');

		Route::resource('details', 'DetailController');

		Route::get('details/{detail}/delete', 'DetailController@delete')->name('detail.delete');

		Route::resource('dates', 'DateController');

		Route::get('dates/{date}/delete', 'DateController@delete')->name('date.delete');

		Route::get('logout', 'AdminController@logout')->name('logout');

		Route::get('home', 'AdminController@home')->name('home');

		Route::get('change/password', 'AdminController@password')->name('password');

		Route::post('change/password', 'AdminController@changePassword')->name('change-password');

	});

});

Route::get('/{vue?}', function() {
    return view('welcome');
})->where('vue', '[\/\w\.-]*');

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use File;
use Carbon\Carbon;

class Item extends Model
{
    /**
     * The database table used by the model.
     */

    protected $table = 'items';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'slug', 'image', 'category_id', 'tiny_description', 'description', 'banner', 'location', 'duration', 'difficulty_level', 'sleeping_bag_rental', 'cost', 'payment_link', 'meta_title', 'meta_description', 'meta_keywords', 'media_title', 'diff_cost_one', 'diff_cost_one_label', 'diff_cost_two', 'diff_cost_two_label', 'diff_cost_three', 'diff_cost_three_label'
    ];

    public function category() {
        return $this->belongsTo('App\Category');
    }
    
    public function testimonials() {
        return $this->morphMany('App\Testimonial', 'testimonialable');
    }

    public function images() {
        return $this->morphMany('App\Image', 'imageable');
    }

    public function details() {
        return $this->hasMany('App\Detail', 'item_id')->orderBy('order');
    }

    public function dates() {
        return $this->hasMany('App\Date', 'item_id');
    }

    public function upcoming() {
        return $this->hasMany('App\Date', 'item_id')->whereDate('event_date', '>', Carbon::yesterday())->orderBy('event_date');
    }

    public function upcomingone() {
        return $this->hasMany('App\Date', 'item_id')->whereDate('event_date', '>', Carbon::yesterday())->orderBy('event_date')->take(1);
    }

    public function getInclusionsAttribute($inclusions) {
        return explode(',', $inclusions);
    }

    public function getExclusionsAttribute($exclusions) {
        return explode(',', $exclusions);
    }

    public function setImageAttribute($image) {

        if(gettype($image) === 'string') {

            $this->attributes['image'] = $image;

        } else {

            if($image) {

                if(isset($this->attributes['image'])) {

                    if($this->attributes['image'] != '') {

                        File::delete($this->attributes['image']);

                    }

                }

                $imageName = sha1(time()).'.'.$image->getClientOriginalExtension(); 

                $directory = 'uploads/item/images'; 

                if(!File::exists($directory)) {
                    File::makeDirectory($directory, 0775, true);
                }

                $path = $directory.'/'.$imageName;

                $image->move($directory, $imageName);

                $this->attributes['image'] = $path;

            }

        }    
    }

    public function setBannerAttribute($banner) {

        if(gettype($banner) === 'string') {

            $this->attributes['banner'] = $banner;

        } else {

            if($banner) {

                if(isset($this->attributes['banner'])) {

                    if($this->attributes['banner'] != '') {

                        File::delete($this->attributes['banner']);

                    }

                }

                $bannerName = sha1(time()).'banner.'.$banner->getClientOriginalExtension(); 

                $directory = 'uploads/category/images'; 

                if(!File::exists($directory)) {
                    File::makeDirectory($directory, 0775, true);
                }

                $path = $directory.'/'.$bannerName;

                $banner->move($directory, $bannerName);

                $this->attributes['banner'] = $path;

            }

        }    
    }

    public static function slugify($name) {
        $slug = preg_replace('/ /', '-', $name); 
        $slug = strtolower($slug);
        return $slug;
    }

}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Item;
use App\Category;
use Session, File;
use App\Http\Requests;
use App\Date;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Item::paginate(10);

        return view('admin.item.index')->with('items', $items);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::pluck('name', 'id');

        return view('admin.item.create')->with('categories', $categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\ItemRequest $request)
    {   
        $trip = Item::create($request->all() + ['slug' => Item::slugify($request->name), 'hide' => isset($request->hide) ? 1 : 0]);

        if($trip){

            Session::flash('success', 'Trip created!!');
            return redirect()->route('trips.index');

        } else {

            Session::flash('error', 'Please try again.');
            return redirect()->back();

        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Item $item)
    {
        $images = $item->images;

        $details = $item->details()->orderBy('order')->get();

        $dates = $item->dates()->orderBy('event_date')->get();

        return view('admin.item.show')->with('item', $item)->with('images', $images)->with('details', $details)->with('dates', $dates);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $item)
    {
        $categories = Category::pluck('name', 'id');

        return view('admin.item.edit')->with('categories', $categories)->with('item', $item);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\ItemRequest $request, Item $item)
    {

        $update = $item->update($request->all() + ['slug' => Item::slugify($request->name), 'hide' => isset($request->hide) ? 1 : 0]);

        if($update){

            Session::flash('success', 'Trip edited!!');
            return redirect()->route('trips.index');

        } else {

            Session::flash('error', 'Please try again.');
            return redirect()->back();

        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete(Item $item)
    {
        if($item->image != "") {

            File::delete($item->image);
            
        }

        $delete = $item->delete();

        if($delete){

            Session::flash('success', 'Trip deleted!!');
            return redirect()->route('trips.index');

        } else {

            Session::flash('error', 'Please try again.');
            return redirect()->back();

        }

    }

    public function trips(Request $request) {
        
        $query = Date::join('items', 'dates.item_id', '=', 'items.id')->join('categories', 'categories.id', '=', 'items.category_id')->whereDate('event_date', '>', Carbon::yesterday());

        if(isset($request->name)) {
            $query->whereHas('item', function($q) use ($request) {
                $q->where('name', 'LIKE', '%'.$request->name.'%');
            });
        }

        if(isset($request->category_id) && $request->category_id != '') {
            $query->whereHas('item', function($q) use ($request) {
                $q->where('category_id', $request->category_id);
            });
        }

        if(isset($request->month) && $request->month != '') { 
            $query->whereMonth('event_date', $request->month);
        }
        
        $trips = $query->select('dates.id as date_id', 'dates.event_date', 'dates.event_end_date', 'dates.cost as date_cost', 'items.*', 'categories.name as category_name')->orderBy('event_date')->paginate(9);

        $filterurl = "";

        foreach ($request->all() as $key => $value) {

            if($key == "page") {

                $filterurl = $filterurl;

            } else {

                $filterurl = $filterurl ."&".$key."=".$value;

            }

        }

        return response()->json([
            'status' => 'Success',
            'trips' => view('frontend.ajax.trips')->with('trips', $trips)->with('input', $filterurl)->render(),
        ], 200);

    }

    public function tripProfile($slug) {

        $trip = Item::with('category')->with('upcoming')->with('images')->with('details')->where('slug', $slug)->firstOrFail();

        $testimonial = $trip->testimonials()->orderBy(DB::raw('RAND()'))->first();

        return response()->json([
            'status' => 'Success',
            'task' => 'Fetch Category',
            'trip' => $trip,
            'testimonial' => $testimonial ? $testimonial : null
        ], 200);

    }

    public function upcomingTrips() {

        $trips = Date::join('items', 'dates.item_id', '=', 'items.id')->join('categories', 'categories.id', '=', 'items.category_id')->whereDate('event_date', '>', Carbon::yesterday())->orderBy('event_date')->take(3)->get();

        $trips = $this->formatTrips($trips, 'Date');

        return response()->json([
            'status' => 'Success',
            'task' => 'Fetch Trips',
            'trips' => $trips
        ], 200);

    }

    public function formatTrips($trips, $criteria = null) { 

        $formattedtrips = [];

        if($criteria) {

            foreach ($trips as $trip) { 

                $item = [];
                
                $item['id'] = $trip->date_id;
                $item['name'] = $trip->name;
                $item['slug'] = $trip->slug;
                $item['tiny_description'] = $trip->tiny_description;
                $item['image'] = $trip->image;
                $item['cost'] = $trip->cost;
                $item['event_date'] = $trip->event_date; 
                $item['category_name'] = $trip->item ? $trip->item->category->name : $trip->category_name; 
                   
    
                array_push($formattedtrips, $item); 
            }

        } else {

            foreach ($trips as $trip) { 

                $item = [];
                
                $item['id'] = $trip->id;
                $item['name'] = $trip->name;
                $item['slug'] = $trip->slug;
                $item['tiny_description'] = $trip->tiny_description;
                $item['image'] = $trip->image;
                $item['cost'] = $trip->cost;
                $item['category_name'] = $trip->category_name; 
                $item['event_date'] = '';
    
                array_push($formattedtrips, $item); 
            }

        }

        

        return $formattedtrips;
    }
    
}

resources/views/admin/item/partials/details.blade.php
<h5>Details Section</h5>
{{ Form::open(['route' => 'details.store']) }}
	
	@include('admin.details.partials.form')

{{ Form::close() }}
	
<div class="row" style="margin-top:20px;">
	<div class="col-sm-12 accordion" id="detail-accordian">
	@foreach($details as $detail) 
		<div class="card">
			<div class="card-header" id="headingOne">
				<h2 class="mb-0">
					<a class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse{{ $detail->id }}">
					{{ $detail->title }}</a>
					<a class="btn btn-danger float-right" href="{{ route('detail.delete', $detail->id) }}">Delete</a>
					<a class="btn btn-info float-right" style="margin-right:5px;" href="{{ route('details.edit', $detail->id) }}" target="_blank">Edit</a>
					<button class="btn btn-warning float-right" style="margin-right:5px;">{{ $detail->order }}</button>
				</h2>
			</div>
			<div id="collapse{{ $detail->id }}" class="collapse" aria-labelledby="heading" data-parent="#detail-accordian">
				<div class="card-body">
					{!! $detail->text !!}
				</div>
			</div>
		</div>
	@endforeach
	</div>
</div>

resources/views/admin/item/partials/form.blade.php
<div class="form-group">
	<label>Name</label>
	{!! Form::text('name', null, ['placeholder' => 'Name','class' => 'form-control new-form-control', 'id' => 'name']) !!}
	@if($errors->has('name'))
	<p class="form-error">{{ $errors->first('name') }} <span class="glyphicon glyphicon-remove-circle"></span> </p>
	@endif
</div>

<div class="form-group">
	<label>Category</label>
	{!! Form::select('category_id', $categories, null, array('placeholder' => 'Select Categories','class' => 'form-control new-form-control', 'id' => 'category_id')) !!}
	@if($errors->has('category_id'))
	<p class="form-error">{{ $errors->first('category_id') }} <span class="glyphicon glyphicon-remove-circle"></span> </p>
	@endif
</div>

<div class="form-group">
	<label>Tiny Description</label>
	{!! Form::textarea('tiny_description', null, ['placeholder' => 'Tiny Description...','class' => 'form-control new-form-control', 'id' => 'tiny_description', 'rows' => 6]) !!}
	@if($errors->has('tiny_description'))
	<p class="form-error">{{ $errors->first('tiny_description') }} <span class="glyphicon glyphicon-remove-circle"></span> </p>
	@endif
</div>

<div class="form-group">
	<label>Description</label>
	{!! Form::textarea('description', null, ['placeholder' => 'Description...','class' => 'form-control new-form-control', 'id' => 'description', 'rows' => 6]) !!}
	@if($errors->has('description'))
	<p class="form-error">{{ $errors->first('description') }} <span class="glyphicon glyphicon-remove-circle"></span> </p>
	@endif
</div>



<div class="form-group">
	<label>Image</label> <br>
	@if(isset($item))
	<img src="{{ url($item->image) }}" alt="" class="img-thumbnail" style="height:100px;">
	@endif
	<br><br>
	{!! Form::file('image') !!}
	@if($errors->has('image'))
	<p class="form-error">{{ $errors->first('image') }} <span class="glyphicon glyphicon-remove-circle"></span> </p>
	@endif
</div>

<div class="form-group">
	<label>Banner</label> <br>
	@if(isset($item))
	<img src="{{ url($item->banner) }}" alt=""  class="img-thumbnail" style="height:100px;">
	@endif
	<br><br>
	{!! Form::file('banner') !!}
	@if($errors->has('banner'))
	<p class="form-error">{{ $errors->first('banner') }} <span class="glyphicon glyphicon-remove-circle"></span> </p>
	@endif
</div>

<div class="form-group">
	<label>Difficulty Level</label>
	{!! Form::select('difficulty_level', ['Easy' => 'Easy'], null, array('placeholder' => 'Select Categories','class' => 'form-control new-form-control', 'id' => 'difficulty_level')) !!}
	@if($errors->has('difficulty_level'))
	<p class="form-error">{{ $errors->first('difficulty_level') }} <span class="glyphicon glyphicon-remove-circle"></span> </p>
	@endif
</div>

<div class="form-group">
	<label>Cost (Rs.)</label>
	{!! Form::text('cost', null, ['placeholder' => 'Eg. 3000.','class' => 'form-control new-form-control', 'id' => 'cost']) !!}
	@if($errors->has('cost'))
	<p class="form-error">{{ $errors->first('cost') }} <span class="glyphicon glyphicon-remove-circle"></span> </p>
	@endif
</div>

<div class="form-group">
	<label>Cost Label - 1</label>
	{!! Form::text('diff_cost_one_label', null, ['placeholder' => 'Eg Vagafam.','class' => 'form-control new-form-control', 'id' => 'diff_cost_one_label']) !!}
	@if($errors->has('diff_cost_one_label'))
	<p class="form-error">{{ $errors->first('diff_cost_one_label') }} <span class="glyphicon glyphicon-remove-circle"></span> </p>
	@endif
</div>

<div class="form-group">
	<label>Cost (Rs.) - 1</label>
	{!! Form::text('diff_cost_one', null, ['placeholder' => 'Eg. 3000.','class' => 'form-control new-form-control', 'id' => 'diff_cost_one']) !!}
	@if($errors->has('diff_cost_one'))
	<p class="form-error">{{ $errors->first('diff_cost_one') }} <span class="glyphicon glyphicon-remove-circle"></span> </p>
	@endif
</div>

<div class="form-group">
	<label>Cost Label - 2</label>
	{!! Form::text('diff_cost_two_label', null, ['placeholder' => 'Eg. BYOT.','class' => 'form-control new-form-control', 'id' => 'diff_cost_two_label']) !!}
	@if($errors->has('diff_cost_two_label'))
	<p class="form-error">{{ $errors->first('diff_cost_two_label') }} <span class="glyphicon glyphicon-remove-circle"></span> </p>
	@endif
</div>

<div class="form-group">
	<label>Cost (Rs.) - 2</label>
	{!! Form::text('diff_cost_two', null, ['placeholder' => 'Eg. 3000.','class' => 'form-control new-form-control', 'id' => 'diff_cost_two']) !!}
	@if($errors->has('diff_cost_two'))
	<p class="form-error">{{ $errors->first('diff_cost_two') }} <span class="glyphicon glyphicon-remove-circle"></span> </p>
	@endif
</div>

<div class="form-group">
	<label>Cost Label - 3</label>
	{!! Form::text('diff_cost_three_label', null, ['placeholder' => 'Eg. Group.','class' => 'form-control new-form-control', 'id' => 'diff_cost_three_label']) !!}
	@if($errors->has('diff_cost_three_label'))
	<p class="form-error">{{ $errors->first('diff_cost_three_label') }} <span class="glyphicon glyphicon-remove-circle"></span> </p>
	@endif
</div>

<div class="form-group">
	<label>Cost (Rs.) - 3</label>
	{!! Form::text('diff_cost_three', null, ['placeholder' => 'Eg. 3000.','class' => 'form-control new-form-control', 'id' => 'diff_cost_three']) !!}
	@if($errors->has('diff_cost_three'))
	<p class="form-error">{{ $errors->first('diff_cost_three') }} <span class="glyphicon glyphicon-remove-circle"></span> </p>
	@endif
</div>

<div class="form-group">
	<label>Location</label>
	{!! Form::text('location', null, ['placeholder' => 'Eg. Parvati Valley, Himachal Pradesh.','class' => 'form-control new-form-control', 'id' => 'location']) !!}
	@if($errors->has('location'))
	<p class="form-error">{{ $errors->first('location') }} <span class="glyphicon glyphicon-remove-circle"></span> </p>
	@endif
</div>

<div class="form-group">
	<label>Duration</label>
	{!! Form::text('duration', null, ['placeholder' => 'Eg. 2D/3N.','class' => 'form-control new-form-control', 'id' => 'duration']) !!}
	@if($errors->has('duration'))
	<p class="form-error">{{ $errors->first('duration') }} <span class="glyphicon glyphicon-remove-circle"></span> </p>
	@endif
</div>

<div class="form-group">
	<label>Payment Link</label>
	{!! Form::text('payment_link', null, ['placeholder' => '','class' => 'form-control new-form-control', 'id' => 'payment_link']) !!}
	@if($errors->has('payment_link'))
	<p class="form-error">{{ $errors->first('payment_link') }} <span class="glyphicon glyphicon-remove-circle"></span> </p>
	@endif
</div>

<div class="form-group">
	<label for="hide">Hide</label>
	{!! Form::checkbox('hide', '1') !!}
</div>

<div class="form-group">
	<label>Meta Title</label>
	{!! Form::text('meta_title', null, ['placeholder' => 'Meta Title','class' => 'form-control new-form-control', 'id' => 'meta_title']) !!}
	@if($errors->has('meta_title'))
	<p class="form-error">{{ $errors->first('meta_title') }} <span class="glyphicon glyphicon-remove-circle"></span> </p>
	@endif
</div>

<div class="form-group">
	<label>Meta Description</label>
	{!! Form::textarea('meta_description', null, ['placeholder' => 'Meta Description...','class' => 'form-control new-form-control', 'id' => 'meta_description', 'rows' => 6]) !!}
	@if($errors->has('meta_description'))
	<p class="form-error">{{ $errors->first('meta_description') }} <span class="glyphicon glyphicon-remove-circle"></span> </p>
	@endif
</div>

<div class="form-group">
	<label>Meta Keywords</label>
	{!! Form::textarea('meta_keywords', null, ['placeholder' => 'Meta Keywords...','class' => 'form-control new-form-control', 'id' => 'meta_keywords', 'rows' => 6]) !!}
	@if($errors->has('meta_keywords'))
	<p class="form-error">{{ $errors->first('meta_keywords') }} <span class="glyphicon glyphicon-remove-circle"></span> </p>
	@endif
</div>

<div class="form-group">
	<label>Media Title</label>
	{!! Form::text('media_title', null, ['placeholder' => 'Media Title','class' => 'form-control new-form-control', 'id' => 'media_title']) !!}
	@if($errors->has('media_title'))
	<p class="form-error">{{ $errors->first('media_title') }} <span class="glyphicon glyphicon-remove-circle"></span> </p>
	@endif
</div>

<button type="submit" class="btn btn-primary">Submit</button>

resources/views/admin/item/partials/images.blade.php
<h5>Add Images</h5>
{{ Form::open(['route' => 'images.store', 'files' => true]) }}
	
	<div class="form-group">
		<label>Image</label> <br>
		{!! Form::file('image') !!}
		@if($errors->has('image'))
		<p class="form-error">{{ $errors->first('image') }} <span class="glyphicon glyphicon-remove-circle"></span> </p>
		@endif
	</div>

	{{ Form::hidden('imageable_id', $item->id) }}		
	{{ Form::hidden('imageable_type', 'App\Item') }}		

	<button type="submit" class="btn btn-primary">Submit</button>

{{ Form::close() }}
	
<div class="row" style="margin-top:20px;">
@foreach($images as $image) 
	<div class="col-sm-12">
		<div style="width:100%; position: relative;">
			<img width="100%" src="{{ url($image->image) }}" class="img-thumbnail">
			<a href="{{ route('image.delete', $image->id) }}" class="close-button"><img src="{{ asset('img/close.svg') }}"></a>
		</div>
	</div>

@endforeach
</div>