routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@home')->name('index');

Route::get('/aboutus', 'HomeController@aboutus')->name('aboutus');

Route::get('/contact', 'HomeController@contact')->name('contact');

Route::get('/terms-and-conditions', 'HomeController@terms')->name('terms');

Route::get('/office-outdoors', 'HomeController@officeOutdoors')->name('office-outdoors');

Route::get('/vagafam', 'HomeController@vagafam')->name('vagafam');

Route::get('category/{slug}', 'HomeController@categoryProfile')->name('category-profile');

Route::get('trip/{slug}/{when?}', 'HomeController@tripProfile')->name('trip-profile');

Route::get('upcoming-trips', 'HomeController@experiences')->name('experiences');

Route::post('vagafam-form', 'HomeController@vagafamForm')->name('vagafam.form');

Route::post('officeoutdoors-form', 'HomeController@officeoutdoorsForm')->name('officeoutdoors.form');

Route::post('contact-form', 'HomeController@contactForm')->name('contact.form');

Route::middleware('guest')->group(function () {

	Route::get('login', 'LoginController@loginPage')->name('login-page');

	Route::post('login', 'LoginController@login')->name('login');

});

Route::middleware('auth')->group(function () {

	Route::prefix('admin')->group(function () {

		Route::resource('testimonials', 'TestimonialController');

		Route::get('testimonials/{testimonial}/delete', 'TestimonialController@delete')->name('testimonial.delete');

		Route::resource('slides', 'SlideController');

		Route::get('slides/{slide}/delete', 'SlideController@delete')->name('slide.delete');	

		Route::resource('category', 'CategoryController');

		Route::get('category/{category}/delete', 'CategoryController@delete')->name('category.delete');	

		Route::post('category/{category}/icon', 'CategoryController@icon')->name('category.icon');

		Route::get('category/{category}/icon/delete', 'CategoryController@iconDelete')->name('category.icon.delete');	

		Route::resource('trips', 'ItemController');

		Route::get('trip/{trip}/delete', 'ItemController@delete')->name('trip.delete');

		Route::resource('images', 'ImageController');

		Route::get('images/{image}/delete', 'ImageController@delete')->name('image.delete');

		Route::resource('artists', 'ArtistController');

		Route::get('artists/{artist}/delete', 'ArtistController@delete')->name('artist.delete');

		Route::resource('details', 'DetailController');

		Route::get('details/{detail}/delete', 'DetailController@delete')->name('detail.delete');

		Route::resource('dates', 'DateController');

		Route::get('dates/{date}/delete', 'DateController@delete')->name('date.delete');

		Route::get('logout', 'AdminController@logout')->name('logout');

		Route::get('home', 'AdminController@home')->name('home');

		Route::get('change/password', 'AdminController@password')->name('password');

		Route::post('change/password', 'AdminController@changePassword')->name('change-password');

	});

});

Route::get('/{vue?}', function() {
    return view('welcome');
})->where('vue', '[\/\w\.-]*');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Admin Panel - @yield('title')</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{{ asset('css/app.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('trumbowyg/dist/ui/trumbowyg.min.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('tagsinput/jquery.tagsinput.min.css') }}">

	<link rel="apple-touch-icon" sizes="57x57" href="{{ asset('favicon/apple-icon-57x57.png') }}">
	<link rel="apple-touch-icon" sizes="60x60" href="{{ asset('favicon/apple-icon-60x60.png') }}">
	<link rel="apple-touch-icon" sizes="72x72" href="{{ asset('favicon/apple-icon-72x72.png') }}">
	<link rel="apple-touch-icon" sizes="76x76" href="{{ asset('favicon/apple-icon-76x76.png') }}">
	<link rel="apple-touch-icon" sizes="114x114" href="{{ asset('favicon/apple-icon-114x114.png') }}">
	<link rel="apple-touch-icon" sizes="120x120" href="{{ asset('favicon/apple-icon-120x120.png') }}">
	<link rel="apple-touch-icon" sizes="144x144" href="{{ asset('favicon/apple-icon-144x144.png') }}">
	<link rel="apple-touch-icon" sizes="152x152" href="{{ asset('favicon/apple-icon-152x152.png') }}">
	<link rel="apple-touch-icon" sizes="180x180" href="{{ asset('favicon/apple-icon-180x180.png') }}">
	<link rel="icon" type="image/png" sizes="192x192"  href="{{ asset('favicon/android-icon-192x192.png') }}">
	<link rel="icon" type="image/png" sizes="32x32" href="{{ asset('favicon/favicon-32x32.png') }}">
	<link rel="icon" type="image/png" sizes="96x96" href="{{ asset('favicon/favicon-96x96.png') }}">
	<link rel="icon" type="image/png" sizes="16x16" href="{{ asset('favicon/favicon-16x16.png') }}">
	<link rel="manifest" href="{{ asset('favicon/manifest.json') }}">
	<meta name="msapplication-TileColor" content="#ffffff">
	<meta name="msapplication-TileImage" content="{{ asset('favicon/ms-icon-144x144.png') }}">
	<meta name="theme-color" content="#ffffff">
	
	<style type="text/css">
        .flash {
            top: 64px;
            position: fixed;
            right: 10px;
            z-index: 10000;
        }
	</style>
</head>
<body>

	@include('layouts.navbar')

	@include('layouts.flash')
	
	@yield('content')

	<div id="result"></div>
	
	<script src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<script src="{{ asset('trumbowyg/dist/trumbowyg.min.js') }}"></script>
	<script src="{{ asset('tagsinput/jquery.tagsinput.min.js') }}"></script>

	@yield('scripts')

</body>
</html>

resources/views/layouts/flash.blade.php
@if (Session::has('success'))
    <div class="alert alert-success flash alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <strong>Well done! - </strong> {{ Session::get('success') }}
    </div>
@endif 

@if (Session::has('error'))
    <div class="alert alert-danger flash alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <strong>Watch Out! - </strong> {{ Session::get('error') }}
    </div>
@endif

@if (Session::has('info'))
    <div class="alert alert-info flash alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <strong>Heads up! - </strong> {{ Session::get('info') }}
    </div>
@endif 

resources/views/layouts/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Vaga Admin</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            @if(Auth::user())
            <li class="nav-item active">
                <a class="nav-link" href="{{ route('home') }}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('category.index') }}">Categories</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('trips.index') }}">Trips</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('slides.index') }}">Slides</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('testimonials.index') }}">Testimonials</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('change-password') }}">Password</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('logout') }}">Logout</a>
            </li>
            @endif
        </ul>
    </div>
</nav>